site_name: Automotive Grade Linux Documentation Site
site_url: http://agl-docs.readthedocs.io/
site_author: Shankho Boron Ghosh
theme_dir: hacks/
theme: 
  name: alabaster
  ##include_sidebar: False
  #include_homepage_in_sidebar: False
  #navigation_depth: 1
  collapse_navigation: False
  # titles_only: True
  

plugins:
  - search:
      separator: '[\s\-\_]+'


